New Pull Request
floatkeera/wthr. pull request #8
Opened 2018-08-08 14:46 UTC by BensonCasey7

2018-08-08 14:47 UTC, floatkeera approved these changes
good

2018-08-08 18:53 UTC, floatkeera requested changes

2018-08-08 18:53 UTC, floatkeera commented on README.md
> -- npmf
not good

2018-08-08 18:53 UTC, BensonCasey7 commented on README.md
> -- npmf
@floatkeera test

2018-08-08 18:55 UTC, floatkeera submitted a review, later dismissed

2018-08-08 18:58 UTC, floatkeera commented on README.md
> -- npmf
@BensonCasey7  hello

2018-08-08 19:32 UTC, floatkeera submitted a review, later dismissed

2018-08-09 21:34 UTC, floatkeera submitted a review, later dismissed

2018-08-10 16:45 UTC, BensonCasey7 commented on README.md
> -- npmf
tets

2018-08-10 16:46 UTC, BensonCasey7 commented
testing

2018-08-10 16:46 UTC, floatkeera commented
asdfasdf

2018-08-10 16:46 UTC, BensonCasey7 commented
@floatkeera

2018-08-10 16:58 UTC, floatkeera commented on README.md
> -- npmf
lol

2018-08-10 17:42 UTC, floatkeera approved these changes

2018-08-10 17:43 UTC, merged